### ISSUE TITLE
problem in laravel 8

### ISSUE THREAD

**Issue by P-Shakibafar** [kavenegar/kavenegar-laravel#34]
InvalidArgumentException
Driver [kavenegar] not supported.

**Comment by shm379** [comment]
i have same problem

**Comment by P-Shakibafar** [comment]
Fixed in last pull request.

**Comment by hosseinRezaei188** [comment]
in last update laravel 8 has been support

**Comment by WiGeeky** [comment]
@hosseinRezaei188 The problem is still present within the latest packagist version (1.3.2). Please consider merging the suggested pull request.

**Comment by ariaieboy** [comment]
> in last update laravel 8 has been support

i've installed 1.3.2 and the problem is not resolved yet

merge pull request #35 or change the via method of the https://github.com/kavenegar/kavenegar-laravel/blob/34ea6dad71d88597995736235536da20e95e6b54/src/Notification/KavenegarBaseNotification.php#L21
like this:

`
    /**
     * Get the notification's delivery channel.
     *
     * @param mixed $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return [KavenegarChannel::class];
    }
`

**Comment by ariaieboy** [comment]
can u please tag this as a release so we can get the last changes using composer

**Comment by Rasool-deldar** [comment]
s
